// Vinyl Radar — aanbevelingen & vondsten
// cat: "A" = DJ/wijnbar · "B" = Thuis luisteren · "C" = Crate-digging
// crate (A): 1 cosmic · 2 reggae/dub · 3 laidback hiphop · 4 world/Afro/Latin · 5 funky soul/jazz-funk · 6 disco/funk/party
window.VINYL_DATA = [
  // ---------- A — DJ / wijnbar ----------
  { id:"a1", cat:"A", artist:"Lonnie Liston Smith & The Cosmic Echoes", title:"Expansions", year:1975, country:"US",
    tracks:["Expansions","A Chance for Peace","Summer Nights"], crate:[1,5], energy:3, pLo:15, pHi:22,
    element:"Zwevende Rhodes + hypnotische bas", desc:"De letterlijke blauwdruk van cosmic groove; bouwt traag op." },
  { id:"a2", cat:"A", artist:"Azymuth", title:"Light as a Feather", year:1979, country:"Brazilië",
    tracks:["Jazz Carnival","Fly Over the Horizon","Partido Alto"], crate:[1,6], energy:4, pLo:14, pHi:20,
    element:"Braziliaanse jazz-funk, Rhodes-drenched", desc:"Zweeft én danst — recht in je Mildlife/Khruangbin-hoek." },
  { id:"a3", cat:"A", artist:"Cymande", title:"Cymande", year:1972, country:"UK/Guyana",
    tracks:["Bra","Dove","The Message","Zion I"], crate:[4,5], energy:3, pLo:16, pHi:22,
    element:"Afro-funk met dubby ruimte", desc:"Warm, groovy, een beetje vreemd — tracks nemen de tijd." },
  { id:"a4", cat:"A", artist:"Bobbi Humphrey", title:"Blacks and Blues", year:1974, country:"US",
    tracks:["Chicago, Damn","Harlem River Drive","Blacks and Blues"], crate:[5,1], energy:3, pLo:18, pHi:26,
    element:"Mizell jazz-funk, fluit + Rhodes", desc:"Zwoele headnod-groove." },
  { id:"a5", cat:"A", artist:"Mulatu Astatke", title:"Mulatu of Ethiopia", year:1972, country:"Ethiopië",
    tracks:["Mulatu","Kulunmanqueleshi","Kasalefkut-Hulu"], crate:[1,4], energy:2, pLo:18, pHi:24,
    element:"Ethio-jazz + vibrafoon", desc:"Hypnotisch en net-genoeg-vreemd; perfecte opener." },
  { id:"a6", cat:"A", artist:"Idris Muhammad", title:"Power of Soul", year:1974, country:"US",
    tracks:["Loran's Dance","Power of Soul","Piece of Mind"], crate:[5], energy:3, pLo:15, pHi:25,
    element:"Losse, diepe drums + Rhodes", desc:"CTI jazz-funk die heerlijk opbouwt." },
  { id:"a7", cat:"A", artist:"Donald Byrd", title:"Places and Spaces", year:1975, country:"US",
    tracks:["Change (Makes You Want to Hustle)","Dominoes","Wind Parade"], crate:[5,6], energy:4, pLo:12, pHi:20,
    element:"Cosmic funk richting dansbaar", desc:"De brug van headnod naar vloer." },
  { id:"a8", cat:"A", artist:"Dexter Wansel", title:"Life on Mars", year:1976, country:"US",
    tracks:["Life on Mars","Theme from the Planets","Together Once Again"], crate:[1,6], energy:4, pLo:15, pHi:22,
    element:"Philly cosmic-disco, synths/Rhodes", desc:"Ruimtelijk én dansbaar; ondergewaardeerd juweel." },
  { id:"a9", cat:"A", artist:"Manu Dibango", title:"Soul Makossa", year:1972, country:"Kameroen",
    tracks:["Soul Makossa","Lily","Dangwa"], crate:[4,6], energy:4, pLo:14, pHi:22,
    element:"Afro-funk die doorstuwt", desc:"Party zonder cheese." },
  { id:"a10", cat:"A", artist:"WAR", title:"The World Is a Ghetto", year:1972, country:"US",
    tracks:["The World Is a Ghetto","City, Country, City","Four Cornered Room"], crate:[4,5], energy:3, pLo:8, pHi:15,
    element:"Trage, rokerige builds", desc:"Precies je 'de tijd nemen'; bodemprijs, topwaarde." },
  { id:"a11", cat:"A", artist:"Mandrill", title:"Composite Truth", year:1973, country:"US",
    tracks:["Fencewalk","Hang Loose","Polk Street Carnival"], crate:[5,4], energy:4, pLo:10, pHi:18,
    element:"Afro-Latin funk + percussie-lagen", desc:"Rauw en dansbaar." },
  { id:"a12", cat:"A", artist:"Augustus Pablo", title:"King Tubby Meets Rockers Uptown", year:1976, country:"Jamaica",
    tracks:["King Tubby Meets the Rockers Uptown","Each One Dub","555 Dub Street"], crate:[2,1], energy:2, pLo:16, pHi:22,
    element:"Melodica-dub, hypnotisch", desc:"Dé plaat voor je zwevende openingsfase." },
  { id:"a13", cat:"A", artist:"Lee Perry & The Upsetters", title:"Super Ape", year:1976, country:"Jamaica",
    tracks:["Zion's Blood","Croaking Lizard","Dread Lion"], crate:[2,1], energy:2, pLo:15, pHi:22,
    element:"Cosmic dub, vreemd en warm", desc:"Natuurlijke match naast Fat Freddy's." },
  { id:"a14", cat:"A", artist:"Madlib", title:"Shades of Blue", year:2003, country:"US",
    tracks:["Slim's Return","Distant Land","Mystic Bounce"], crate:[3,5], energy:3, pLo:20, pHi:26,
    element:"Blue Note-jazz herbouwd tot hiphop", desc:"Wijnbar-lijm richting head-nod." },
  { id:"a15", cat:"A", artist:"Quantic", title:"The 5th Exotic", year:2001, country:"UK",
    tracks:["Time Is the Enemy","Life in the Rain","Meet Me in Rio"], crate:[3,5], energy:3, pLo:14, pHi:20,
    element:"Downtempo soul-funk, live-groove", desc:"Ongedwongen, warm, niet-obvious." },
  { id:"a16", cat:"A", artist:"Gil Scott-Heron & Brian Jackson", title:"Winter in America", year:1974, country:"US",
    tracks:["The Bottle","Rivers of My Fathers","A Very Precious Time"], crate:[5], energy:3, pLo:12, pHi:20,
    element:"Rhodes-soul met ziel", desc:"En een dancefloor-troef ('The Bottle')." },
  { id:"a17", cat:"A", artist:"Ohio Players", title:"Skin Tight", year:1974, country:"US",
    tracks:["Skin Tight","Jive Turkey","Heaven Must Be Like This"], crate:[6], energy:4, pLo:8, pHi:15,
    element:"Vette dancefloor-funk", desc:"Voor de piek; bodemprijs, topwaarde." },
  { id:"a18", cat:"A", artist:"Patrice Rushen", title:"Pizzazz", year:1979, country:"US",
    tracks:["Haven't You Heard","Let the Music Take Me","Settle for My Love"], crate:[6], energy:4, pLo:15, pHi:25,
    element:"Cosmic-boogie", desc:"Einde van de avond zonder bruiloft-disco." },
  { id:"a19", cat:"A", artist:"Various", title:"The Roots of Chicha: Psychedelic Cumbias from Peru", year:2007, country:"Peru",
    tracks:["Los Destellos – Elsa","Juaneco y Su Combo – Vacilando con Ayahuasca","Los Diablos Rojos – Meshkalina"], crate:[4], energy:3, pLo:16, pHi:22,
    element:"Psychedelische cumbia + wah-gitaar", desc:"Je Money Chicha-ader, maar de bron." },
  { id:"a20", cat:"A", artist:"Marcos Valle", title:"Previsão do Tempo", year:1973, country:"Brazilië",
    tracks:["Mentira","Os Ganhadores da Vida","Previsão do Tempo"], crate:[1,4], energy:3, pLo:18, pHi:24,
    element:"Braziliaanse cosmic-soul (met Azymuth)", desc:"Warm, dromerig, groovy." },

  // ---------- B — Thuis luisteren ----------
  { id:"b1", cat:"B", artist:"Kyuss", title:"Welcome to Sky Valley", year:1994, country:"US", pick:true,
    tracks:["Gardenia","Demon Cleaner","Space Cadet"], sublane:"stoner/desert", pLo:22, pHi:30,
    element:"Warme fuzz + woestijn-groove + dynamiek", desc:"De essentiële Kyuss die je mist." },
  { id:"b2", cat:"B", artist:"Fu Manchu", title:"The Action Is Go", year:1997, country:"US",
    tracks:["Evil Eye","Saturn III","The Action Is Go"], sublane:"stoner/desert", pLo:20, pHi:30,
    element:"Fuzz-rollende desert-groove", desc:"Geen fratsen, puur stuwen." },
  { id:"b3", cat:"B", artist:"Elder", title:"Reflections of a Floating World", year:2017, country:"US", pick:true,
    tracks:["Sanctuary","The Falling Age","Staving Off Truth"], sublane:"prog-stoner", pLo:25, pHi:32,
    element:"Lange psychedelische builds + dynamiek", desc:"Waar Tool en Kyuss elkaar raken." },
  { id:"b4", cat:"B", artist:"All Them Witches", title:"Dying Surfer Meets His Maker", year:2015, country:"US", pick:true,
    tracks:["Dirt Preachers","El Centro","Open Passageways"], sublane:"dark psych", pLo:22, pHi:28,
    element:"Donkere psych-groove + dubby spanning", desc:"Je snijvlak van hypnotisch en zwaar." },
  { id:"b5", cat:"B", artist:"Earthless", title:"From the Ages", year:2013, country:"US",
    tracks:["Violence of the Red Sea","From the Ages"], sublane:"heavy-psych (instr.)", pLo:25, pHi:32,
    element:"Instrumentale jams die eindeloos opbouwen", desc:"Hendrix meets Sabbath in de woestijn." },
  { id:"b6", cat:"B", artist:"Sleep", title:"Dopesmoker", year:1999, country:"US", pick:true,
    tracks:["Dopesmoker","Sonic Titan"], sublane:"doom", pLo:26, pHi:36,
    element:"Eén rif, een uur, ritueel", desc:"De ultieme 'de tijd nemen'-plaat." },
  { id:"b7", cat:"B", artist:"Electric Wizard", title:"Dopethrone", year:2000, country:"UK",
    tracks:["Funeralopolis","Vinum Sabbathi","Weird Tales"], sublane:"doom", pLo:28, pHi:38,
    element:"Zwaarste, donkerste, verdovend", desc:"Hypnotische doom." },
  { id:"b8", cat:"B", artist:"YOB", title:"Clearing the Path to Ascend", year:2014, country:"US",
    tracks:["Marrow","In Our Blood"], sublane:"doom", pLo:25, pHi:32,
    element:"Van fluister naar verpletterend", desc:"Meditatieve, dynamische doom." },
  { id:"b9", cat:"B", artist:"Pallbearer", title:"Sorrow and Extinction", year:2012, country:"US",
    tracks:["Foreigner","Given to the Grave"], sublane:"doom", pLo:22, pHi:30,
    element:"Melodische, emotionele doom + dynamiek", desc:"Zwaar maar warm." },
  { id:"b10", cat:"B", artist:"Isis", title:"Oceanic", year:2002, country:"US", pick:true,
    tracks:["The Beginning and the End","Weight","Carry"], sublane:"post-metal", pLo:28, pHi:40,
    element:"Golvend tussen zacht en beukend", desc:"Dé Tool-adjacent aanrader." },
  { id:"b11", cat:"B", artist:"Neurosis", title:"Through Silver in Blood", year:1996, country:"US",
    tracks:["Through Silver in Blood","Locust Star"], sublane:"post-metal", pLo:28, pHi:35,
    element:"Ritualistisch, tribaal, dynamisch", desc:"De godfathers van dit geluid." },
  { id:"b12", cat:"B", artist:"Baroness", title:"Red Album", year:2007, country:"US",
    tracks:["Isak","Wanderlust","Rays on Pinion"], sublane:"prog-sludge", pLo:25, pHi:32,
    element:"Melodische sludge met riffs + kleur", desc:"Mastodon-energie, eigen sfeer." },
  { id:"b13", cat:"B", artist:"Russian Circles", title:"Memorial", year:2013, country:"US",
    tracks:["Deficit","1777","Memorial"], sublane:"post-metal (instr.)", pLo:22, pHi:30,
    element:"Filmisch, van ijl naar loodzwaar", desc:"Instrumentaal, dynamisch." },
  { id:"b14", cat:"B", artist:"Graveyard", title:"Hisingen Blues", year:2011, country:"Zweden", pick:true,
    tracks:["Ain't Fit to Live Here","Uncomfortably Slow","Hisingen Blues"], sublane:"heavy-blues", pLo:20, pHi:28,
    element:"Retro-heavy blues met donkere groove", desc:"Je DeWolff-hoek maar rauwer." },
  { id:"b15", cat:"B", artist:"Uncle Acid & the Deadbeats", title:"Blood Lust", year:2011, country:"UK",
    tracks:["I'll Cut You Down","Death's Door","Ritual Knife"], sublane:"retro-psych-doom", pLo:25, pHi:32,
    element:"Donker lo-fi retro-psych + griezelige melodie", desc:"Sinister en catchy." },
  { id:"b16", cat:"B", artist:"Clutch", title:"Blast Tyrant", year:2004, country:"US",
    tracks:["The Mob Goes Wild","Cypress Grove","The Regulator"], sublane:"groove-riff", pLo:25, pHi:32,
    element:"Groove-riff-machine met karakter", desc:"Nooit generiek; swagger." },
  { id:"b17", cat:"B", artist:"Chelsea Wolfe", title:"Abyss", year:2015, country:"US",
    tracks:["Carrion Flowers","Iron Moon","After the Fall"], sublane:"dark-experimenteel", pLo:22, pHi:30,
    element:"Zwaar, atmosferisch, dreigend", desc:"Doom-gothic met elektronische randen." },
  { id:"b18", cat:"B", artist:"Boris", title:"Pink", year:2005, country:"Japan",
    tracks:["Farewell","Pink","Woman on the Screen"], sublane:"heavy-psych/noise", pLo:28, pHi:38,
    element:"Heavy-psych, noise en shoegaze dooreen", desc:"Avontuurlijk en overweldigend." },

  // ---------- C — Crate-digging ----------
  { id:"c1", cat:"C", artist:"Grover Washington Jr.", title:"Mister Magic", year:1975, country:"US",
    tracks:["Mister Magic","Black Frost"], pLo:5, pHi:10,
    element:"Warme Rhodes-jazz-funk + rollende bas", desc:"Iedereen skipt 'm, onterecht." },
  { id:"c2", cat:"C", artist:"Bob James", title:"Two", year:1975, country:"US",
    tracks:["Nautilus","Take Me to the Mardi Gras"], pLo:6, pHi:12,
    element:"Breakbeat-groove + spacey arrangement", desc:"Meest gesamplede cheap-bin-plaat ooit." },
  { id:"c3", cat:"C", artist:"El Chicano", title:"Viva Tirado", year:1970, country:"US/Chicano",
    tracks:["Viva Tirado","Coming Home Baby"], pLo:5, pHi:12,
    element:"Latin-soul-jazz, Hammond + percussie", desc:"Hypnotisch traag; vergeten." },
  { id:"c4", cat:"C", artist:"Malo", title:"Malo", year:1972, country:"US/Latin",
    tracks:["Suavecito","Pana","Café"], pLo:5, pHi:12,
    element:"Latin-rock, brass + wah-gitaar", desc:"Santana's broertje Jorge; altijd in de bak." },
  { id:"c5", cat:"C", artist:"Osibisa", title:"Woyaya", year:1972, country:"Ghana/UK",
    tracks:["Woyaya","Y Sharp","Spirits Up Above"], pLo:6, pHi:14,
    element:"Afro-rock, percussie-lagen die opbouwen", desc:"Wereldinvloed + warmte." },
  { id:"c6", cat:"C", artist:"Cal Tjader", title:"Soul Sauce", year:1965, country:"US/Latin",
    tracks:["Soul Sauce (Guachi Guaro)","Afro Blue"], pLo:6, pHi:12,
    element:"Vibrafoon + Latin-percussie", desc:"Luchtig hypnotisch — jouw vibrafoon-ding." },
  { id:"c7", cat:"C", artist:"Mtume", title:"Juicy Fruit", year:1983, country:"US",
    tracks:["Juicy Fruit","Would You Like to (Fool Around)"], pLo:5, pHi:10,
    element:"Spacey boogie-synths + dikke bas + ruimte", desc:"Dub-gevoel in boogie-vorm." },
  { id:"c8", cat:"C", artist:"Jorge Ben", title:"África Brasil", year:1976, country:"Brazilië",
    tracks:["Ponta de Lança Africano (Umbabarauma)","Xica da Silva","Taj Mahal"], pLo:12, pHi:20,
    element:"Samba-funk + wereldritme dat doorstuwt", desc:"Iets duurder, absurde waarde." },
  { id:"c9", cat:"C", artist:"Ramsey Lewis", title:"Sun Goddess", year:1974, country:"US",
    tracks:["Sun Goddess","Hot Dawgit"], pLo:5, pHi:10,
    element:"EW&F-groove + Rhodes/synth-zon", desc:"Maurice White speelt mee." },
  { id:"c10", cat:"C", artist:"Gábor Szabó", title:"Dreams", year:1968, country:"Hongarije/US",
    tracks:["Galatea's Guitar","The Fortune Teller"], pLo:8, pHi:15,
    element:"Psychedelische jazz-gitaar + ritme", desc:"Warm-weird, dromerige sfeer." },
  { id:"c11", cat:"C", artist:"Mustafa Özkent", title:"Gençlik İle Elele", year:1973, country:"Turkije", wildcard:true,
    tracks:["Lokum","Silent Dervish","Emmioğlu"], pLo:18, pHi:24,
    element:"Turkse funk-psych, wah + fuzz + break-drums", desc:"'Wat ís dit' van formaat." },
  { id:"c12", cat:"C", artist:"Miles Davis", title:"On the Corner", year:1972, country:"US", wildcard:true,
    tracks:["On the Corner","Black Satin"], pLo:18, pHi:25,
    element:"Chaotische funk-jazz + wah + hypnose", desc:"De vuile, funky Miles." },
  { id:"c13", cat:"C", artist:"Can", title:"Future Days", year:1973, country:"Duitsland", wildcard:true,
    tracks:["Future Days","Moonshake","Bel Air"], pLo:18, pHi:25,
    element:"Motorische hypnose + dubby ruimte", desc:"Recht in je 'langzaam ontvouwen'-hart." },
  { id:"c14", cat:"C", artist:"Sun Ra", title:"Lanquidity", year:1978, country:"US", wildcard:true,
    tracks:["Lanquidity","Where Pathways Meet"], pLo:20, pHi:28,
    element:"Cosmic jazz-funk + spacey synths + weirdness", desc:"Weirdness met een groove eronder." },
  { id:"c15", cat:"C", artist:"Goat", title:"World Music", year:2012, country:"Zweden", wildcard:true,
    tracks:["Diarabi","Run to Your Mama","Let It Bleed"], pLo:20, pHi:25,
    element:"Ritueel Afro-psych + fuzz + percussie", desc:"Modern maar rauw/vuil — géén nette retro." },

  // ---------- Live vondsten (Discogs API-geverifieerd) ----------
  { id:"r-20260830-1", cat:"C", artist:"Les McCann & Eddie Harris", title:"Swiss Movement", year:1969, country:"US",
    tracks:["Compared to What","Cold Duck Time","You Got It in Your Soulness"], pLo:1, pHi:8,
    element:"Soul-jazz met Rhodes + live-groove (Compared to What)", desc:"Bak-goud: 35 exemplaren, spotgoedkoop.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/5497886?sort=price&sort_order=asc",
    askPrice:0.99, shipEst:14, numForSale:35, found:"2026-08-30" },
  { id:"r-20260830-2", cat:"C", artist:"Barrabas", title:"Wild Safari", year:1972, country:"Spanje", wildcard:true,
    tracks:["Wild Safari","Woman","Move"], pLo:12, pHi:20,
    element:"Spaanse funk-rock, percussie + wah-groove", desc:"Onverwacht groovy; 🃏 wildcard onder de €15.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/1269681?sort=price&sort_order=asc",
    askPrice:14.87, shipEst:7, numForSale:23, found:"2026-08-30" },

  // ---------- Vondsten 2026-08-30 ronde 2 ----------
  { id:"r-20260830-3", cat:"A", artist:"Herbie Hancock", title:"Head Hunters", year:1973, country:"US",
    tracks:["Chameleon","Watermelon Man","Sly"], element:"Wah-clavinet + elektrische bas + hypnotische funk-groove",
    desc:"Dé jazz-funk plaat; 'Chameleon' ontvouwt 15 min pure groove.",
    crate:[5], energy:4, pLo:5, pHi:15, wildcard:false, pick:false,
    source:"Discogs", url:"https://www.discogs.com/sell/release/31381?sort=price&sort_order=asc",
    askPrice:5.14, numForSale:43, cond:"", seller:"", found:"2026-08-30" },

  { id:"r-20260830-4", cat:"A", artist:"Kool & The Gang", title:"Wild and Peaceful", year:1973, country:"US",
    tracks:["Funky Stuff","Jungle Boogie","Hollywood Swinging"], element:"Rauw groepsgeluid, dikke horns + losse funk-drums",
    desc:"Pre-commercieel Kool: de echte raw funk, voor het peakuur.",
    crate:[5,6], energy:4, pLo:6, pHi:14, wildcard:false, pick:false,
    source:"Discogs", url:"https://www.discogs.com/sell/release/3279109?sort=price&sort_order=asc",
    askPrice:6.44, numForSale:12, cond:"", seller:"", found:"2026-08-30" },

  { id:"r-20260830-5", cat:"A", artist:"The Blackbyrds", title:"Flying Start", year:1974, country:"US",
    tracks:["Walking in Rhythm","The Baby","Flying Start"], element:"Mizell-productie: Rhodes + sax + warme groove",
    desc:"Donald Byrd's leerlingen spelen de warmste jazz-funk; 'Walking in Rhythm' is pure headnod.",
    crate:[5], energy:3, pLo:2, pHi:8, wildcard:false, pick:false,
    source:"Discogs", url:"https://www.discogs.com/sell/release/839130?sort=price&sort_order=asc",
    askPrice:2.32, numForSale:35, cond:"", seller:"", found:"2026-08-30" },

  { id:"r-20260830-6", cat:"A", artist:"Sly & The Family Stone", title:"There's a Riot Goin' On", year:1971, country:"US",
    tracks:["Luv N' Haight","Family Affair","Thank You for Talkin' to Me Africa"], element:"Donkere murky psych-funk, slepende hypnose",
    desc:"Sly op zijn donkerst: anti-commercieel, bevreemdend, maar onmiskenbaar groovy.",
    crate:[1], energy:2, pLo:2, pHi:8, wildcard:true, pick:false,
    source:"Discogs", url:"https://www.discogs.com/sell/release/5431106?sort=price&sort_order=asc",
    askPrice:1.72, numForSale:31, cond:"", seller:"", found:"2026-08-30" },

  { id:"r-20260830-7", cat:"B", artist:"Radio Moscow", title:"Brain Cycles", year:2009, country:"US",
    tracks:["Gettin' Better","Ransom","Death of a Dog"], element:"Psych-blues fuzz met echte groove + vuile analoge productie",
    desc:"Parker Griggs speelt alles zelf; de rauwste authentieke heavy-blues van dit decennium.",
    sublane:"heavy-blues/retro-psych", pLo:18, pHi:25, wildcard:false, pick:false,
    source:"Discogs", url:"https://www.discogs.com/sell/release/5169321?sort=price&sort_order=asc",
    askPrice:18.15, numForSale:22, cond:"", seller:"", found:"2026-08-30" },

  { id:"r-20260830-8", cat:"B", artist:"Alice Coltrane", title:"Journey in Satchidananda", year:1971, country:"US",
    tracks:["Journey in Satchidananda","Shiva-Loka","Stopover Bombay"], element:"Harp + Pharoah Sanders sax + meditatieve kosmische flow",
    desc:"Spirituele tegenhanger van je zware kant; Alice op haar meest kosmisch en hypnotisch.",
    sublane:"spiritual jazz", pLo:25, pHi:35, wildcard:false, pick:false,
    source:"Discogs", url:"https://www.discogs.com/sell/release/15016343?sort=price&sort_order=asc",
    askPrice:25.79, numForSale:23, cond:"", seller:"", found:"2026-08-30" },

  { id:"r-20260830-9", cat:"C", artist:"George Duke", title:"Reach for It", year:1977, country:"US",
    tracks:["Reach for It","Dukey Stick","Searchin'"], element:"Funky synths + dikke bas + dancefloor-energie",
    desc:"Altijd in de goedkopenbak voor bijna niets — titelnummer en 'Dukey Stick' zijn echte groovers.",
    pLo:1, pHi:6, wildcard:false, pick:false,
    source:"Discogs", url:"https://www.discogs.com/sell/release/50494?sort=price&sort_order=asc",
    askPrice:0.85, numForSale:68, cond:"", seller:"", found:"2026-08-30" },

  { id:"r-20260830-10", cat:"C", artist:"Rotary Connection", title:"Peace", year:1968, country:"US",
    tracks:["I Am the Black Gold of the Sun","Peace at Least","Turn Me On"], element:"Psychedelische soul-orchestratie + Minnie Riperton stem",
    desc:"Vroegste Minnie Riperton; bizar arrangement dat nergens heen gaat dan precies goed — 🃏 'I Am the Black Gold of the Sun' is later nuyorican-sample-goud.",
    pLo:12, pHi:18, wildcard:true, pick:false,
    source:"Discogs", url:"https://www.discogs.com/sell/release/1534189?sort=price&sort_order=asc",
    askPrice:12.0, numForSale:22, cond:"", seller:"", found:"2026-08-30" }
];
