// Vinyl Radar — aanbevelingen & vondsten
// cat: "A" = DJ/wijnbar · "B" = Thuis luisteren · "C" = Crate-digging
// crate (A): 1 cosmic · 2 reggae/dub · 3 laidback hiphop · 4 world/Afro/Latin · 5 funky soul/jazz-funk · 6 disco/funk/party
window.VINYL_DATA = [
  // ---------- A — DJ / wijnbar ----------
  { id:"a1", cat:"A", sublane:"mystic groove", artist:"Lonnie Liston Smith & The Cosmic Echoes", title:"Expansions", year:1975, country:"US",
    tracks:["Expansions","A Chance for Peace","Summer Nights"], crate:[1,5], energy:3, pLo:15, pHi:22,
    element:"Zwevende Rhodes + hypnotische bas", desc:"De letterlijke blauwdruk van cosmic groove; bouwt traag op." },
  { id:"a2", cat:"A", artist:"Azymuth", title:"Light as a Feather", year:1979, country:"Brazilië",
    tracks:["Jazz Carnival","Fly Over the Horizon","Partido Alto"], crate:[1,6], energy:4, pLo:14, pHi:20,
    element:"Braziliaanse jazz-funk, Rhodes-drenched", desc:"Zweeft én danst — recht in je Mildlife/Khruangbin-hoek." },
  { id:"a3", cat:"A", sublane:"mystic groove", artist:"Cymande", title:"Cymande", year:1972, country:"UK/Guyana",
    tracks:["Bra","Dove","The Message","Zion I"], crate:[4,5], energy:3, pLo:16, pHi:22,
    element:"Afro-funk met dubby ruimte", desc:"Warm, groovy, een beetje vreemd — tracks nemen de tijd." },
  { id:"a4", cat:"A", artist:"Bobbi Humphrey", title:"Blacks and Blues", year:1974, country:"US",
    tracks:["Chicago, Damn","Harlem River Drive","Blacks and Blues"], crate:[5,1], energy:3, pLo:18, pHi:26,
    element:"Mizell jazz-funk, fluit + Rhodes", desc:"Zwoele headnod-groove." },
  { id:"a5", cat:"A", sublane:"mystic groove", artist:"Mulatu Astatke", title:"Mulatu of Ethiopia", year:1972, country:"Ethiopië",
    tracks:["Mulatu","Kulunmanqueleshi","Kasalefkut-Hulu"], crate:[1,4], energy:2, pLo:18, pHi:24,
    element:"Ethio-jazz + vibrafoon", desc:"Hypnotisch en net-genoeg-vreemd; perfecte opener." },
  { id:"a6", cat:"A", sublane:"mystic groove", artist:"Idris Muhammad", title:"Power of Soul", year:1974, country:"US",
    tracks:["Loran's Dance","Power of Soul","Piece of Mind"], crate:[5], energy:3, pLo:15, pHi:25,
    element:"Losse, diepe drums + Rhodes", desc:"CTI jazz-funk die heerlijk opbouwt." },
  { id:"a7", cat:"A", sublane:"mystic groove", artist:"Donald Byrd", title:"Places and Spaces", year:1975, country:"US",
    tracks:["Change (Makes You Want to Hustle)","Dominoes","Wind Parade"], crate:[5,6], energy:4, pLo:12, pHi:20,
    element:"Cosmic funk richting dansbaar", desc:"De brug van headnod naar vloer." },
  { id:"a8", cat:"A", artist:"Dexter Wansel", title:"Life on Mars", year:1976, country:"US",
    tracks:["Life on Mars","Theme from the Planets","Together Once Again"], crate:[1,6], energy:4, pLo:15, pHi:22,
    element:"Philly cosmic-disco, synths/Rhodes", desc:"Ruimtelijk én dansbaar; ondergewaardeerd juweel." },
  { id:"a9", cat:"A", artist:"Manu Dibango", title:"Soul Makossa", year:1972, country:"Kameroen",
    tracks:["Soul Makossa","Lily","Dangwa"], crate:[4,6], energy:4, pLo:14, pHi:22,
    element:"Afro-funk die doorstuwt", desc:"Party zonder cheese." },
  { id:"a10", cat:"A", artist:"WAR", title:"The World Is a Ghetto", year:1972, country:"US",
    tracks:["The World Is a Ghetto","City, Country, City","Four Cornered Room"], crate:[4,5], energy:3, pLo:8, pHi:15,
    element:"Trage, rokerige builds", desc:"Precies je 'de tijd nemen'; bodemprijs, topwaarde." },
  { id:"a11", cat:"A", artist:"Mandrill", title:"Composite Truth", year:1973, country:"US",
    tracks:["Fencewalk","Hang Loose","Polk Street Carnival"], crate:[5,4], energy:4, pLo:10, pHi:18,
    element:"Afro-Latin funk + percussie-lagen", desc:"Rauw en dansbaar." },
  { id:"a12", cat:"A", artist:"Augustus Pablo", title:"King Tubby Meets Rockers Uptown", year:1976, country:"Jamaica",
    tracks:["King Tubby Meets the Rockers Uptown","Each One Dub","555 Dub Street"], crate:[2,1], energy:2, pLo:16, pHi:22,
    element:"Melodica-dub, hypnotisch", desc:"Dé plaat voor je zwevende openingsfase." },
  { id:"a13", cat:"A", artist:"Lee Perry & The Upsetters", title:"Super Ape", year:1976, country:"Jamaica",
    tracks:["Zion's Blood","Croaking Lizard","Dread Lion"], crate:[2,1], energy:2, pLo:15, pHi:22,
    element:"Cosmic dub, vreemd en warm", desc:"Natuurlijke match naast Fat Freddy's." },
  { id:"a14", cat:"A", artist:"Madlib", title:"Shades of Blue", year:2003, country:"US",
    tracks:["Slim's Return","Distant Land","Mystic Bounce"], crate:[3,5], energy:3, pLo:20, pHi:26,
    element:"Blue Note-jazz herbouwd tot hiphop", desc:"Wijnbar-lijm richting head-nod." },
  { id:"a15", cat:"A", artist:"Quantic", title:"The 5th Exotic", year:2001, country:"UK",
    tracks:["Time Is the Enemy","Life in the Rain","Meet Me in Rio"], crate:[3,5], energy:3, pLo:14, pHi:20,
    element:"Downtempo soul-funk, live-groove", desc:"Ongedwongen, warm, niet-obvious." },
  { id:"a16", cat:"A", artist:"Gil Scott-Heron & Brian Jackson", title:"Winter in America", year:1974, country:"US",
    tracks:["The Bottle","Rivers of My Fathers","A Very Precious Time"], crate:[5], energy:3, pLo:12, pHi:20,
    element:"Rhodes-soul met ziel", desc:"En een dancefloor-troef ('The Bottle')." },
  { id:"a17", cat:"A", artist:"Ohio Players", title:"Skin Tight", year:1974, country:"US",
    tracks:["Skin Tight","Jive Turkey","Heaven Must Be Like This"], crate:[6], energy:4, pLo:8, pHi:15,
    element:"Vette dancefloor-funk", desc:"Voor de piek; bodemprijs, topwaarde." },
  { id:"a18", cat:"A", artist:"Patrice Rushen", title:"Pizzazz", year:1979, country:"US",
    tracks:["Haven't You Heard","Let the Music Take Me","Settle for My Love"], crate:[6], energy:4, pLo:15, pHi:25,
    element:"Cosmic-boogie", desc:"Einde van de avond zonder bruiloft-disco." },
  { id:"a19", cat:"A", artist:"Various", title:"The Roots of Chicha: Psychedelic Cumbias from Peru", year:2007, country:"Peru",
    tracks:["Los Destellos – Elsa","Juaneco y Su Combo – Vacilando con Ayahuasca","Los Diablos Rojos – Meshkalina"], crate:[4], energy:3, pLo:16, pHi:22,
    element:"Psychedelische cumbia + wah-gitaar", desc:"Je Money Chicha-ader, maar de bron." },
  { id:"a20", cat:"A", artist:"Marcos Valle", title:"Previsão do Tempo", year:1973, country:"Brazilië",
    tracks:["Mentira","Os Ganhadores da Vida","Previsão do Tempo"], crate:[1,4], energy:3, pLo:18, pHi:24,
    element:"Braziliaanse cosmic-soul (met Azymuth)", desc:"Warm, dromerig, groovy." },

  // ---------- B — Thuis luisteren ----------
  { id:"b1", cat:"B", artist:"Kyuss", title:"Welcome to Sky Valley", year:1994, country:"US", pick:true,
    tracks:["Gardenia","Demon Cleaner","Space Cadet"], sublane:"stoner/desert", pLo:22, pHi:30,
    element:"Warme fuzz + woestijn-groove + dynamiek", desc:"De essentiële Kyuss die je mist." },
  { id:"b2", cat:"B", artist:"Fu Manchu", title:"The Action Is Go", year:1997, country:"US",
    tracks:["Evil Eye","Saturn III","The Action Is Go"], sublane:"stoner/desert", pLo:20, pHi:30,
    element:"Fuzz-rollende desert-groove", desc:"Geen fratsen, puur stuwen." },
  { id:"b3", cat:"B", artist:"Elder", title:"Reflections of a Floating World", year:2017, country:"US", pick:true,
    tracks:["Sanctuary","The Falling Age","Staving Off Truth"], sublane:"prog-stoner", pLo:25, pHi:32,
    element:"Lange psychedelische builds + dynamiek", desc:"Waar Tool en Kyuss elkaar raken." },
  { id:"b4", cat:"B", artist:"All Them Witches", title:"Dying Surfer Meets His Maker", year:2015, country:"US", pick:true,
    tracks:["Dirt Preachers","El Centro","Open Passageways"], sublane:"dark psych", pLo:22, pHi:28,
    element:"Donkere psych-groove + dubby spanning", desc:"Je snijvlak van hypnotisch en zwaar." },
  { id:"b5", cat:"B", artist:"Earthless", title:"From the Ages", year:2013, country:"US",
    tracks:["Violence of the Red Sea","From the Ages"], sublane:"heavy-psych (instr.)", pLo:25, pHi:32,
    element:"Instrumentale jams die eindeloos opbouwen", desc:"Hendrix meets Sabbath in de woestijn." },
  { id:"b6", cat:"B", artist:"Sleep", title:"Dopesmoker", year:1999, country:"US", pick:true,
    tracks:["Dopesmoker","Sonic Titan"], sublane:"doom", pLo:26, pHi:36,
    element:"Eén rif, een uur, ritueel", desc:"De ultieme 'de tijd nemen'-plaat." },
  { id:"b7", cat:"B", artist:"Electric Wizard", title:"Dopethrone", year:2000, country:"UK",
    tracks:["Funeralopolis","Vinum Sabbathi","Weird Tales"], sublane:"doom", pLo:28, pHi:38,
    element:"Zwaarste, donkerste, verdovend", desc:"Hypnotische doom." },
  { id:"b8", cat:"B", artist:"YOB", title:"Clearing the Path to Ascend", year:2014, country:"US",
    tracks:["Marrow","In Our Blood"], sublane:"doom", pLo:25, pHi:32,
    element:"Van fluister naar verpletterend", desc:"Meditatieve, dynamische doom." },
  { id:"b9", cat:"B", artist:"Pallbearer", title:"Sorrow and Extinction", year:2012, country:"US",
    tracks:["Foreigner","Given to the Grave"], sublane:"doom", pLo:22, pHi:30,
    element:"Melodische, emotionele doom + dynamiek", desc:"Zwaar maar warm." },
  { id:"b10", cat:"B", artist:"Isis", title:"Oceanic", year:2002, country:"US", pick:true,
    tracks:["The Beginning and the End","Weight","Carry"], sublane:"post-metal", pLo:28, pHi:40,
    element:"Golvend tussen zacht en beukend", desc:"Dé Tool-adjacent aanrader." },
  { id:"b11", cat:"B", artist:"Neurosis", title:"Through Silver in Blood", year:1996, country:"US",
    tracks:["Through Silver in Blood","Locust Star"], sublane:"post-metal", pLo:28, pHi:35,
    element:"Ritualistisch, tribaal, dynamisch", desc:"De godfathers van dit geluid." },
  { id:"b12", cat:"B", artist:"Baroness", title:"Red Album", year:2007, country:"US",
    tracks:["Isak","Wanderlust","Rays on Pinion"], sublane:"prog-sludge", pLo:25, pHi:32,
    element:"Melodische sludge met riffs + kleur", desc:"Mastodon-energie, eigen sfeer." },
  { id:"b13", cat:"B", artist:"Russian Circles", title:"Memorial", year:2013, country:"US",
    tracks:["Deficit","1777","Memorial"], sublane:"post-metal (instr.)", pLo:22, pHi:30,
    element:"Filmisch, van ijl naar loodzwaar", desc:"Instrumentaal, dynamisch." },
  { id:"b14", cat:"B", artist:"Graveyard", title:"Hisingen Blues", year:2011, country:"Zweden", pick:true,
    tracks:["Ain't Fit to Live Here","Uncomfortably Slow","Hisingen Blues"], sublane:"heavy-blues", pLo:20, pHi:28,
    element:"Retro-heavy blues met donkere groove", desc:"Je DeWolff-hoek maar rauwer." },
  { id:"b15", cat:"B", artist:"Uncle Acid & the Deadbeats", title:"Blood Lust", year:2011, country:"UK",
    tracks:["I'll Cut You Down","Death's Door","Ritual Knife"], sublane:"retro-psych-doom", pLo:25, pHi:32,
    element:"Donker lo-fi retro-psych + griezelige melodie", desc:"Sinister en catchy." },
  { id:"b16", cat:"B", artist:"Clutch", title:"Blast Tyrant", year:2004, country:"US",
    tracks:["The Mob Goes Wild","Cypress Grove","The Regulator"], sublane:"groove-riff", pLo:25, pHi:32,
    element:"Groove-riff-machine met karakter", desc:"Nooit generiek; swagger." },
  { id:"b17", cat:"B", artist:"Chelsea Wolfe", title:"Abyss", year:2015, country:"US",
    tracks:["Carrion Flowers","Iron Moon","After the Fall"], sublane:"dark-experimenteel", pLo:22, pHi:30,
    element:"Zwaar, atmosferisch, dreigend", desc:"Doom-gothic met elektronische randen." },
  { id:"b18", cat:"B", artist:"Boris", title:"Pink", year:2005, country:"Japan",
    tracks:["Farewell","Pink","Woman on the Screen"], sublane:"heavy-psych/noise", pLo:28, pHi:38,
    element:"Heavy-psych, noise en shoegaze dooreen", desc:"Avontuurlijk en overweldigend." },

  // ---------- C — Crate-digging ----------
  { id:"c1", cat:"C", artist:"Grover Washington Jr.", title:"Mister Magic", year:1975, country:"US",
    tracks:["Mister Magic","Black Frost"], pLo:5, pHi:10,
    element:"Warme Rhodes-jazz-funk + rollende bas", desc:"Iedereen skipt 'm, onterecht." },
  { id:"c2", cat:"C", artist:"Bob James", title:"Two", year:1975, country:"US",
    tracks:["Nautilus","Take Me to the Mardi Gras"], pLo:6, pHi:12,
    element:"Breakbeat-groove + spacey arrangement", desc:"Meest gesamplede cheap-bin-plaat ooit." },
  { id:"c3", cat:"C", artist:"El Chicano", title:"Viva Tirado", year:1970, country:"US/Chicano",
    tracks:["Viva Tirado","Coming Home Baby"], pLo:5, pHi:12,
    element:"Latin-soul-jazz, Hammond + percussie", desc:"Hypnotisch traag; vergeten." },
  { id:"c4", cat:"C", artist:"Malo", title:"Malo", year:1972, country:"US/Latin",
    tracks:["Suavecito","Pana","Café"], pLo:5, pHi:12,
    element:"Latin-rock, brass + wah-gitaar", desc:"Santana's broertje Jorge; altijd in de bak." },
  { id:"c5", cat:"C", artist:"Osibisa", title:"Woyaya", year:1972, country:"Ghana/UK",
    tracks:["Woyaya","Y Sharp","Spirits Up Above"], pLo:6, pHi:14,
    element:"Afro-rock, percussie-lagen die opbouwen", desc:"Wereldinvloed + warmte." },
  { id:"c6", cat:"C", artist:"Cal Tjader", title:"Soul Sauce", year:1965, country:"US/Latin",
    tracks:["Soul Sauce (Guachi Guaro)","Afro Blue"], pLo:6, pHi:12,
    element:"Vibrafoon + Latin-percussie", desc:"Luchtig hypnotisch — jouw vibrafoon-ding." },
  { id:"c7", cat:"C", artist:"Mtume", title:"Juicy Fruit", year:1983, country:"US",
    tracks:["Juicy Fruit","Would You Like to (Fool Around)"], pLo:5, pHi:10,
    element:"Spacey boogie-synths + dikke bas + ruimte", desc:"Dub-gevoel in boogie-vorm." },
  { id:"c8", cat:"C", artist:"Jorge Ben", title:"África Brasil", year:1976, country:"Brazilië",
    tracks:["Ponta de Lança Africano (Umbabarauma)","Xica da Silva","Taj Mahal"], pLo:12, pHi:20,
    element:"Samba-funk + wereldritme dat doorstuwt", desc:"Iets duurder, absurde waarde." },
  { id:"c9", cat:"C", artist:"Ramsey Lewis", title:"Sun Goddess", year:1974, country:"US",
    tracks:["Sun Goddess","Hot Dawgit"], pLo:5, pHi:10,
    element:"EW&F-groove + Rhodes/synth-zon", desc:"Maurice White speelt mee." },
  { id:"c10", cat:"C", artist:"Gábor Szabó", title:"Dreams", year:1968, country:"Hongarije/US",
    tracks:["Galatea's Guitar","The Fortune Teller"], pLo:8, pHi:15,
    element:"Psychedelische jazz-gitaar + ritme", desc:"Warm-weird, dromerige sfeer." },
  { id:"c11", cat:"C", artist:"Mustafa Özkent", title:"Gençlik İle Elele", year:1973, country:"Turkije", wildcard:true,
    tracks:["Lokum","Silent Dervish","Emmioğlu"], pLo:18, pHi:24,
    element:"Turkse funk-psych, wah + fuzz + break-drums", desc:"'Wat ís dit' van formaat." },
  { id:"c12", cat:"C", artist:"Miles Davis", title:"On the Corner", year:1972, country:"US", wildcard:true,
    tracks:["On the Corner","Black Satin"], pLo:18, pHi:25,
    element:"Chaotische funk-jazz + wah + hypnose", desc:"De vuile, funky Miles." },
  { id:"c13", cat:"C", artist:"Can", title:"Future Days", year:1973, country:"Duitsland", wildcard:true,
    tracks:["Future Days","Moonshake","Bel Air"], pLo:18, pHi:25,
    element:"Motorische hypnose + dubby ruimte", desc:"Recht in je 'langzaam ontvouwen'-hart." },
  { id:"c14", cat:"C", artist:"Sun Ra", title:"Lanquidity", year:1978, country:"US", wildcard:true,
    tracks:["Lanquidity","Where Pathways Meet"], pLo:20, pHi:28,
    element:"Cosmic jazz-funk + spacey synths + weirdness", desc:"Weirdness met een groove eronder." },
  { id:"c15", cat:"C", artist:"Goat", title:"World Music", year:2012, country:"Zweden", wildcard:true,
    tracks:["Diarabi","Run to Your Mama","Let It Bleed"], pLo:20, pHi:25,
    element:"Ritueel Afro-psych + fuzz + percussie", desc:"Modern maar rauw/vuil — géén nette retro." },

  // ---------- Run 2026-08-30 — nieuwe vondsten ----------
  { id:"r-20260830-1", cat:"A", artist:"George Duke", title:"Feel", year:1975, country:"Germany",
    tracks:["Funny Funk","Feel","Cora Jobege","Yana Aminah"], crate:[1,5], energy:3,
    pLo:4, pHi:15, wildcard:false, pick:false,
    element:"jazz-funk Rhodes + exotische wereldsfeer",
    desc:"Vergeten MPS-plaat van Duke vol groove en Afro-Braziliaanse invloeden.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/1159940?sort=price&sort_order=asc",
    askPrice:4.72, shipEst:8, numForSale:36, cond:"", seller:"", found:"2026-08-30" },

  { id:"r-20260830-2", cat:"A", artist:"Altın Gün", title:"Yol", year:2021, country:"Europe",
    tracks:["Yüce Dağ Başında","Ordunun Dereleri","Kara Toprak"], crate:[4], energy:3,
    pLo:22, pHi:32, wildcard:false, pick:false,
    element:"Turkse folk-funk, psychedelische gitaar + ritme",
    desc:"Opvolger van 'On': net zo hypnotisch, nog rauwer en vrijer.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/17562928?sort=price&sort_order=asc",
    askPrice:23.56, shipEst:8, numForSale:75, cond:"", seller:"", found:"2026-08-30" },

  { id:"r-20260830-3", cat:"A", artist:"Bixiga 70", title:"III", year:2015, country:"Germany",
    tracks:["Niran","Di Dancer","Lembe","7 Pancadas"], crate:[4], energy:4,
    pLo:22, pHi:32, wildcard:true, pick:false,
    element:"Braziliaans Afro-funk, rauwe percussie + wereldritme",
    desc:"São Paulo-collectief op Glitterbeat: motorisch Afrobeat met Latijns vuur.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/7131390?sort=price&sort_order=asc",
    askPrice:23.84, shipEst:8, numForSale:23, cond:"", seller:"", found:"2026-08-30" },

  { id:"r-20260830-4", cat:"B", artist:"Graveyard", title:"Lights Out", year:2012, country:"Germany",
    tracks:["Slow Motion Countdown","Endless Night","Hard Times Lovin'"],
    sublane:"heavy-blues", pLo:18, pHi:30, wildcard:false, pick:false,
    element:"Retro heavy-blues met donkere riff + groove",
    desc:"Strakker en donkerder dan Hisingen Blues; zweedse motor op volle toeren.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/3977717?sort=price&sort_order=asc",
    askPrice:20.50, shipEst:8, numForSale:26, cond:"", seller:"", found:"2026-08-30" },

  { id:"r-20260830-5", cat:"B", artist:"Alice Coltrane", title:"Journey in Satchidananda", year:1971, country:"Worldwide",
    tracks:["Journey In Satchidananda","Shiva-Loka","Isis And Osiris"],
    sublane:"spiritual jazz", pLo:25, pHi:38, wildcard:false, pick:false,
    element:"Hypnotische spirituele jazz, harp + tambura + Pharoah Sanders",
    desc:"Meditatieve, kosmische diepte — perfecte tegenhanger van het zwaardere B-materiaal.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/26604263?sort=price&sort_order=asc",
    askPrice:26.65, shipEst:8, numForSale:66, cond:"", seller:"", found:"2026-08-30" },

  { id:"r-20260830-6", cat:"C", artist:"B.T. Express", title:"Energy to Burn", year:1976, country:"UK",
    tracks:["Can't Stop Groovin' Now, Wanna Do It Some More","Energy To Burn","Time Tunnel"],
    pLo:2, pHi:12, wildcard:false, pick:false,
    element:"Rollige 70s R&B-funk, dik bas + dancefloor-drive",
    desc:"UK-persing op <€3: pure dancefloor-engine, standaard in de goedkope bak.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/453415?sort=price&sort_order=asc",
    askPrice:2.94, shipEst:12, numForSale:25, cond:"", seller:"", found:"2026-08-30" },

  { id:"r-20260830-7", cat:"C", artist:"Harari", title:"Harari", year:1981, country:"Netherlands",
    tracks:["Soul Fire","Get Funky","Liven Up"], pLo:18, pHi:28, wildcard:true, pick:false,
    element:"Zuid-Afrikaanse township-funk + Afrobeat-ritme",
    desc:"SA-band (ex-Beaters) op A&M NL: ophalen in NL voor ~€26, onbekend goud.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/3938940?sort=price&sort_order=asc",
    askPrice:22.03, shipEst:4, numForSale:7, cond:"", seller:"", found:"2026-08-30" },

  // ---------- Run 2026-08-30 (2e ronde) — nieuwe vondsten ----------
  { id:"r-20260830-8", cat:"A", artist:"Bobbi Humphrey", title:"Fancy Dancer", year:2021, country:"Worldwide",
    tracks:["Uno Esta","The Trip","You Make Me Feel So Good","Fancy Dancer"], crate:[5,1], energy:3,
    pLo:10, pHi:20, wildcard:false, pick:false,
    element:"Mizell jazz-funk, fluit + Rhodes + Latijns-kosmische groove",
    desc:"Opvolger van Blacks and Blues: zacht, zonnig en net zo hypnotisch — 2021 reissue.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/21040264?sort=price&sort_order=asc",
    askPrice:12.90, shipEst:8, numForSale:84, cond:"", seller:"", sellerUrl:"", found:"2026-08-30" },

  { id:"r-20260830-9", cat:"C", artist:"Ohio Players", title:"Fire", year:1974, country:"Germany",
    tracks:["Fire","Together","Smoke","It's All Over"], pLo:3, pHi:10, wildcard:false, pick:false,
    element:"rollende dancefloor-funk, diepe bas + tight groove",
    desc:"Goedkoopste bak-goud: de German press van hun beste album voor €4 — voor de DJ-piek.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/1186239?sort=price&sort_order=asc",
    askPrice:4.45, shipEst:8, numForSale:12, cond:"", seller:"", sellerUrl:"", found:"2026-08-30" },

  { id:"r-20260830-10", cat:"B", artist:"Mastodon", title:"Crack the Skye", year:2009, country:"Europe",
    tracks:["Oblivion","Quintessence","The Czar","The Last Baron"], sublane:"prog-sludge", pLo:18, pHi:30,
    wildcard:false, pick:false,
    element:"psychedelisch prog-sludge-epos, epische bogen + ruimte + dynamiek",
    desc:"Na Leviathan: zwaarder en kosmischer — Mastodon op hun conceptuele hoogtepunt.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/2077429?sort=price&sort_order=asc",
    askPrice:20.93, shipEst:8, numForSale:28, cond:"", seller:"", sellerUrl:"", found:"2026-08-30" },

  { id:"r-20260830-11", cat:"A", artist:"Cymande", title:"Promised Heights", year:2024, country:"UK & Europe",
    tracks:["Pon De Dungle","Brothers On The Slide","Breezeman","Promised Heights"], crate:[4,5], energy:3,
    pLo:20, pHi:30, wildcard:false, pick:false,
    element:"Afro-funk met dubby ruimte + warme groove",
    desc:"Mindere bekende opvolger van het debuut, net zo groovy — 2024 EU-persing, 56 ex.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/30694411?sort=price&sort_order=asc",
    askPrice:23.18, shipEst:8, numForSale:56, cond:"", seller:"", sellerUrl:"", found:"2026-08-30" },

  { id:"r-20260830-12", cat:"A", artist:"Donald Byrd", title:"Street Lady", year:2023, country:"Europe",
    tracks:["Lansana's Priestess","Miss Kane","Street Lady","Woman Of The World"], crate:[5,1], energy:3,
    pLo:20, pHi:35, wildcard:false, pick:false,
    element:"Mizell-jazz-funk, zwevende Rhodes + kosmische warmte",
    desc:"Donkere, kosmische tegenhanger van Places and Spaces — 180g EU-reissue, 76 ex.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/26604617?sort=price&sort_order=asc",
    askPrice:23.24, shipEst:8, numForSale:76, cond:"", seller:"", sellerUrl:"", found:"2026-08-30" },

  { id:"r-20260830-13", cat:"C", sublane:"mystic groove", artist:"Ronnie Foster", title:"Two Headed Freap", year:2022, country:"Worldwide",
    tracks:["Mystic Brew","The Two Headed Freap","Chunky","Summer Song"], pLo:18, pHi:28, wildcard:true, pick:false,
    element:"Blue Note jazz-funk, organ + Rhodes — 'Mystic Brew' gesampeld door ATCQ",
    desc:"Meest vergeten Mizell-plaat: dromerig, funky, €22 voor de 2022 reissue. 'Wat ís dit?'",
    source:"Discogs", url:"https://www.discogs.com/sell/release/23296742?sort=price&sort_order=asc",
    askPrice:22.09, shipEst:8, numForSale:64, cond:"", seller:"", sellerUrl:"", found:"2026-08-30" },

  // ---------- Run 2026-09-01 — nieuwe vondsten ----------
  { id:"r-20260901-1", cat:"A", artist:"Fela Kuti & The Africa 70", title:"International Thief Thief (I.T.T.)", year:1980, country:"US",
    tracks:["I.T.T. (International Thief Thief) (Part 1)","I.T.T. (International Thief Thief) (Part 2)"], crate:[4], energy:4,
    pLo:12, pHi:25, wildcard:false, pick:false,
    element:"afrobeat-machine + politiek vuur + koper + ritmische hypnose",
    desc:"Langste en felste Fela: 12 min Afrobeat-aanklacht, rauw en onontkoombaar.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/6248681?sort=price&sort_order=asc",
    askPrice:22.00, shipEst:4, numForSale:52, cond:"Mint (M)", seller:"KillaCutz",
    sellerUrl:"https://www.discogs.com/seller/KillaCutz/profile", found:"2026-09-01" },

  { id:"r-20260901-2", cat:"A", artist:"Kool & The Gang", title:"Wild and Peaceful", year:1973, country:"Germany",
    tracks:["Funky Stuff","More Funky Stuff","Jungle Boogie","Heaven At Once"], crate:[5,6], energy:4,
    pLo:10, pHi:18, wildcard:false, pick:false,
    element:"rauwe dancefloor-funk, tight groove + blaas",
    desc:"Funky Stuff en Jungle Boogie op de vroege Kool — vóór de commercialisering.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/583886?sort=price&sort_order=asc",
    askPrice:11.63, shipEst:8, numForSale:25, cond:"", seller:"", sellerUrl:"", found:"2026-09-01" },

  { id:"r-20260901-3", cat:"A", artist:"Lonnie Liston Smith", title:"Loveland", year:1978, country:"Europe",
    tracks:["Sunburst","Journey Into Love","Floating Through Space","Bright Moments"], crate:[1], energy:2,
    pLo:18, pHi:28, wildcard:false, pick:false,
    element:"cosmic Rhodes-soul, drijvend en meditatief",
    desc:"Stiller dan Expansions maar net zo diep — perfecte early-set zweef.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/1688596?sort=price&sort_order=asc",
    askPrice:21.50, shipEst:8, numForSale:10, cond:"", seller:"", sellerUrl:"", found:"2026-09-01" },

  { id:"r-20260901-4", cat:"B", artist:"Can", title:"Tago Mago", year:2014, country:"Europe",
    tracks:["Paperhouse","Mushroom","Oh Yeah","Halleluwah"], sublane:"krautrock/motorisch", pLo:20, pHi:30,
    wildcard:false, pick:false,
    element:"motorische hypnose + rituele drums + vrije ruimte",
    desc:"Future Days' grote broer: langer, rauwer, meer vrije agressie — dé krautrock-plaat.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/5789703?sort=price&sort_order=asc",
    askPrice:23.26, shipEst:8, numForSale:61, cond:"", seller:"", sellerUrl:"", found:"2026-09-01" },

  { id:"r-20260901-5", cat:"C", artist:"Harvey Mason", title:"Marching in the Street", year:1975, country:"Netherlands",
    tracks:["Marching In The Street","Modaji","Hop Scotch","Wild Rice"], pLo:15, pHi:25, wildcard:false, pick:false,
    element:"Mizell-jazz-funk, strakke drums + Rhodes + zacht koper",
    desc:"NL-persing: Harvey Mason als sessie-drummer ontketend — droge groove, rijke productie.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/5059596?sort=price&sort_order=asc",
    askPrice:18.64, shipEst:4, numForSale:5, cond:"", seller:"", sellerUrl:"", found:"2026-09-01" },

  { id:"r-20260901-6", cat:"C", artist:"Ronnie Laws", title:"Fever", year:1976, country:"UK",
    tracks:["Let's Keep It Together","Fever","All The Time"], pLo:6, pHi:15, wildcard:false, pick:false,
    element:"sax-jazz-funk met soul-warmte",
    desc:"Cheap-bin goud: twee instant-grooves voor €7,50 item op UK-persing.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/639863?sort=price&sort_order=asc",
    askPrice:7.50, shipEst:12, numForSale:17, cond:"", seller:"", sellerUrl:"", found:"2026-09-01" },

  { id:"r-20260901-7", cat:"C", artist:"Arthur Verocai", title:"Arthur Verocai", year:2021, country:"UK",
    tracks:["Caboclo","Pelas Sombras","Sylvia","Presente Grego"], pLo:15, pHi:28, wildcard:true, pick:false,
    element:"Braziliaanse orkestrale soul, strijkers + samba + psychedelische spanning",
    desc:"Legendarische lost gem uit 1972: één opname, vergeten 30 jaar — 2021 UK-reissue.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/21188389?sort=price&sort_order=asc",
    askPrice:17.20, shipEst:12, numForSale:10, cond:"", seller:"", sellerUrl:"", found:"2026-09-01" },

  // ---------- Run 2026-09-02 — nieuwe vondsten ----------
  { id:"r-20260902-1", cat:"A", artist:"The Blackbyrds", title:"Flying Start", year:1974, country:"UK",
    tracks:["Flying Start","The Mysterious Vibes","Reggie's Dedication","Cornbread"], crate:[5], energy:4,
    pLo:10, pHi:18, wildcard:false, pick:false,
    element:"Mizell-jazz-funk, Rhodes + zachte blazers + diepe groove",
    desc:"Donald Byrd's studenten op Blue Note: hun debuut vol subtiele Mizell-magie en ziel.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/683698?sort=price&sort_order=asc",
    askPrice:10.99, shipEst:12, numForSale:23, cond:"", seller:"", sellerUrl:"", found:"2026-09-02" },

  { id:"r-20260902-2", cat:"A", artist:"Orchestra Baobab", title:"Specialist In All Styles", year:2002, country:"Europe",
    tracks:["Dee Moo Woor","Bul Ma Mbaye","Niaxarell","Gnima"], crate:[4], energy:3,
    pLo:22, pHi:32, wildcard:true, pick:false,
    element:"Senegalese Afro-Cubaanse groove, diepe ritmesectie + zwoele sax + wereldsfeer",
    desc:"Dakar-legends die Cuba en West-Afrika smelten: tijdloos, zweef-groovy — EU-reissue.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/15970149?sort=price&sort_order=asc",
    askPrice:23.26, shipEst:8, numForSale:7, cond:"", seller:"", sellerUrl:"", found:"2026-09-02" },

  { id:"r-20260902-3", cat:"B", artist:"King Buffalo", title:"Longing to Be the Mountain", year:2018, country:"Europe",
    tracks:["Orion","Longing to Be the Mountain","Cosmonaut"], sublane:"stoner/psych", pLo:20, pHi:30,
    wildcard:false, pick:false,
    element:"Psych-stoner met weidse builds, hypnotisch riff + kosmische ruimte + dynamiek",
    desc:"King Buffalo's zwaarste moment: trager, grooviger, voller — Tool-gevoel via de woestijn.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/12647404?sort=price&sort_order=asc",
    askPrice:21.43, shipEst:8, numForSale:13, cond:"", seller:"", sellerUrl:"", found:"2026-09-02" },

  { id:"r-20260902-4", cat:"B", artist:"Sly & The Family Stone", title:"There's A Riot Goin' On", year:1971, country:"Europe",
    tracks:["Luv N' Haight","Family Affair","(You Caught Me) Smilin'"], sublane:"donker-experimenteel", pLo:18, pHi:30,
    wildcard:true, pick:false,
    element:"Duistere, verdovende funk + hypnotische herhaling + claustrofobische psychedelica",
    desc:"Sly's donkerste uur: murky multi-track chaos, 'Family Affair' is de groove die blijft hangen.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/21308833?sort=price&sort_order=asc",
    askPrice:20.93, shipEst:8, numForSale:88, cond:"", seller:"", sellerUrl:"", found:"2026-09-02" },

  { id:"r-20260902-5", cat:"C", artist:"The Crusaders", title:"Chain Reaction", year:1975, country:"UK",
    tracks:["Keep That Same Old Feeling","Don't Let It Get You Down","Dream Merchant"], pLo:5, pHi:12,
    wildcard:false, pick:false,
    element:"Jazz-funk, wah-gitaar + saxofoon + Stix Hooper-drums — stoer en groovy",
    desc:"Cheap-bin goud: Crusaders in topvorm voor €5,81 — Felder's wah-gitaar zit vol karakter.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/607665?sort=price&sort_order=asc",
    askPrice:5.81, shipEst:12, numForSale:22, cond:"", seller:"", sellerUrl:"", found:"2026-09-02" },

  { id:"r-20260902-6", cat:"C", artist:"Lonnie Smith", title:"Think!", year:1968, country:"USA & Europe",
    tracks:["Slouchin'","Move Your Hand","Spinning Wheel"], pLo:12, pHi:20, wildcard:false, pick:false,
    element:"Hammond-orgel + soul-funk groove — 'Move Your Hand' gesampeld door ATCQ",
    desc:"Blue Note organ-funk klassieker: dikste Hammond-groove in de goedkope bak — 2019 reissue.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/13870751?sort=price&sort_order=asc",
    askPrice:13.76, shipEst:8, numForSale:90, cond:"", seller:"", sellerUrl:"", found:"2026-09-02" },

  { id:"r-20260902-7", cat:"C", artist:"Les McCann & Eddie Harris", title:"Swiss Movement", year:1969, country:"Germany",
    tracks:["Compared to What","Cold Duck Time","Kathleen's Theme"], pLo:12, pHi:22, wildcard:false, pick:false,
    element:"Live soul-jazz + politieke groove — piano + tenor-sax in perfect samenspel",
    desc:"'Compared to What' is één van de beste live-grooves ooit; German press voor €13 is koopje.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/11601911?sort=price&sort_order=asc",
    askPrice:13.48, shipEst:8, numForSale:28, cond:"", seller:"", sellerUrl:"", found:"2026-09-02" },

  // ---------- Run 2026-09-05 — nieuwe vondsten ----------
  { id:"r-20260905-1", cat:"A", artist:"Herbie Hancock", title:"Thrust", year:1974, country:"Europe",
    tracks:["Palm Grease","Butterfly","Actual Proof","Spank-A-Lee"], crate:[5,6], energy:4,
    pLo:22, pHi:32, wildcard:false, pick:false,
    element:"jazz-funk, Rhodes + dikke bas + dansbare groove",
    desc:"Nog grooviger dan Head Hunters: 'Palm Grease' en 'Butterfly' zijn pure dancefloor-funk. 2009 EU-reissue, 70 ex.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/2770412?sort=price&sort_order=asc",
    askPrice:25.58, shipEst:8, numForSale:70, cond:"", seller:"", sellerUrl:"", found:"2026-09-05" },

  { id:"r-20260905-2", cat:"A", artist:"Mulatu Astatke", title:"New York - Addis - London", year:2009, country:"Germany",
    tracks:["Mulatu","Almaz","I Faram Gami I Faram","Yegelle Tezeta"], crate:[1,4], energy:2,
    pLo:22, pHi:32, wildcard:false, pick:false,
    element:"ethio-jazz, vibrafoon + percussie + kosmische sfeer",
    desc:"Compilatie van zijn early masterpieces (1965-1975): alles wat 'Mulatu of Ethiopia' belooft uitgebreid naar een volledige journey. Germany 2009.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/1997304?sort=price&sort_order=asc",
    askPrice:25.58, shipEst:8, numForSale:69, cond:"", seller:"", sellerUrl:"", found:"2026-09-05" },

  { id:"r-20260905-3", cat:"B", artist:"Pharoah Sanders", title:"Karma", year:1969, country:"Worldwide",
    tracks:["The Creator Has a Master Plan","Colors"], sublane:"spiritual jazz", pLo:22, pHi:35,
    wildcard:false, pick:false,
    element:"hypnotische spirituele jazz, sax + percussie + mantra-energie",
    desc:"33 minuten 'The Creator Has a Master Plan': meditatief, ritualistisch, overweldigend — Pharoah's magnum opus. 2022 reissue, 95 ex.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/25484281?sort=price&sort_order=asc",
    askPrice:25.80, shipEst:8, numForSale:95, cond:"", seller:"", sellerUrl:"", found:"2026-09-05" },

  { id:"r-20260905-4", cat:"B", artist:"Windhand", title:"Soma", year:2013, country:"USA & Europe",
    tracks:["Orchard","Cassock","Woodbine","Evergreen"], sublane:"doom/atmosferisch", pLo:24, pHi:34,
    wildcard:false, pick:false,
    element:"atmosferische doom, traag + verdovend + gelaagde droneachtige gitaren",
    desc:"Richmond doom op zijn indrukwekkendst: laag, langzaam, betoverend — als Electric Wizard maar droomeriger en warmer. 2023 reissue.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/28012872?sort=price&sort_order=asc",
    askPrice:26.63, shipEst:8, numForSale:6, cond:"", seller:"", sellerUrl:"", found:"2026-09-05" },

  { id:"r-20260905-5", cat:"C", artist:"Grant Green", title:"Alive!", year:1970, country:"Worldwide",
    tracks:["Down Here on the Ground","Ain't It Funky Now","Let the Music Take You"], pLo:18, pHi:28,
    wildcard:false, pick:false,
    element:"live Blue Note soul-jazz gitaar + funky groove + menselijke energie",
    desc:"Grant Green live in 1970: 'Ain't It Funky Now' is één van de dikste Blue Note-grooves op vinyl. 2019 reissue, 45 ex.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/14404895?sort=price&sort_order=asc",
    askPrice:21.50, shipEst:8, numForSale:45, cond:"", seller:"", sellerUrl:"", found:"2026-09-05" },

  { id:"r-20260905-6", cat:"C", artist:"Norman Connors", title:"You Are My Starship", year:1977, country:"UK",
    tracks:["We Both Need Each Other","You Are My Starship","This Is Your Life"], pLo:3, pHi:10,
    wildcard:false, pick:false,
    element:"cosmic soul-jazz, fluweelzachte groove + Michael Henderson bas",
    desc:"UK-persing voor €4: Norman Connors met Phyllis Hyman — de warmste kosmische soul. Ultieme cheap-bin-goud.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/1610629?sort=price&sort_order=asc",
    askPrice:3.93, shipEst:12, numForSale:6, cond:"", seller:"", sellerUrl:"", found:"2026-09-05" },

  { id:"r-20260905-7", cat:"C", artist:"Herbie Mann", title:"Push Push", year:1971, country:"Germany",
    tracks:["Spirit in the Dark","Push Push","New Orleans"], pLo:6, pHi:14, wildcard:false, pick:false,
    element:"funky fluit + Duane Allman gitaar + blues-soul-jazz crossover",
    desc:"Germany-persing voor €9: Herbie Mann met Duane Allman — funk, blues en jazz in één dikke groove. Vergeten bak-klassiek.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/1687057?sort=price&sort_order=asc",
    askPrice:9.42, shipEst:8, numForSale:15, cond:"", seller:"", sellerUrl:"", found:"2026-09-05" },

  { id:"r-20260905-8", cat:"C", artist:"Barrabas", title:"Barrabas", year:1972, country:"Spain",
    tracks:["Woman","Mamma Mia","Hi-Jack"], pLo:4, pHi:12, wildcard:true, pick:false,
    element:"Spaanse rock-funk crossover, wah-gitaar + rauwe groove + psychedelische energie",
    desc:"Spain-persing voor €5: 'Woman' is een cult-funky hit — absoluut 'wat is dit?'-moment uit de goedkope bak.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/1245094?sort=price&sort_order=asc",
    askPrice:5.16, shipEst:8, numForSale:28, cond:"", seller:"", sellerUrl:"", found:"2026-09-05" },

  // ---------- Run 2026-09-09 — nieuwe vondsten ----------
  { id:"r-20260909-1", cat:"A", artist:"Roy Ayers Ubiquity", title:"Lifeline", year:1977, country:"Europe",
    tracks:["Running Away","Searching","Love from the Sun"], crate:[1,5], energy:3,
    pLo:12, pHi:22, wildcard:false, pick:false,
    element:"cosmic groove + vibrafoon + rhodes, zachte soul-funk warmte",
    desc:"Verzwegen hoogtepunt in de Roy Ayers-catalog: 'Running Away' is pure kosmische headnod-funk. 2017 EU-reissue, 21 ex.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/11717377?sort=price&sort_order=asc",
    askPrice:12.89, shipEst:8, numForSale:21, cond:"", seller:"", sellerUrl:"", found:"2026-09-09" },

  { id:"r-20260909-2", cat:"A", artist:"Fela Kuti & Africa 70", title:"Zombie", year:1977, country:"Europe",
    tracks:["Zombie","Mr. Follow Follow"], crate:[4], energy:4,
    pLo:15, pHi:28, wildcard:false, pick:false,
    element:"afrobeat, hypnotische ritmesectie + koper + politiek vuur",
    desc:"Dé Fela-plaat: 'Zombie' is het perfecte afrobeat-monster — motorisch, meedogenloos, essentieel. 2022 EU-reissue.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/23354300?sort=price&sort_order=asc",
    askPrice:19.74, shipEst:8, numForSale:16, cond:"", seller:"", sellerUrl:"", found:"2026-09-09" },

  { id:"r-20260909-3", cat:"A", artist:"Cymande", title:"Second Time Round", year:1973, country:"Europe",
    tracks:["Anthracite","Willies' Headache","To You"], crate:[4,5], energy:3,
    pLo:18, pHi:30, wildcard:false, pick:false,
    element:"Afro-funk + warme groove + ensemble-spel",
    desc:"Tweede album vlak na het debuut: iets vreemder, net zo groovy — 2023 EU-persing. Perfect naast de eerste Cymande.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/29118112?sort=price&sort_order=asc",
    askPrice:20.20, shipEst:8, numForSale:63, cond:"", seller:"", sellerUrl:"", found:"2026-09-09" },

  { id:"r-20260909-4", cat:"B", artist:"Earthless", title:"Black Heaven", year:2018, country:"Germany",
    tracks:["Volt Rush","Electric Flame","Black Heaven"], sublane:"heavy-psych (instr.)", pLo:18, pHi:30,
    wildcard:false, pick:false,
    element:"instrumentale heavy-psych, Hendrix-riffs + rollende groove + opbouwende dynamiek",
    desc:"Earthless op het hoogtepunt: snellere riffs en grotere dynamische bogen dan From the Ages — Germany 2018.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/11723186?sort=price&sort_order=asc",
    askPrice:22.67, shipEst:8, numForSale:14, cond:"", seller:"", sellerUrl:"", found:"2026-09-09" },

  { id:"r-20260909-5", cat:"B", artist:"Baroness", title:"Blue Record", year:2009, country:"USA & Europe",
    tracks:["Steel That Sleeps The Eye","The Sweetest Curse","Jake Leg"], sublane:"prog-sludge", pLo:22, pHi:35,
    wildcard:false, pick:false,
    element:"melodische prog-sludge, kleurrijke riffs + dynamiek + zang",
    desc:"Baroness' blauwste moment: melodischer dan Red Album maar net zo zwaar — Mastodon-adjacent. 2020 reissue.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/16075339?sort=price&sort_order=asc",
    askPrice:26.38, shipEst:8, numForSale:15, cond:"", seller:"", sellerUrl:"", found:"2026-09-09" },

  { id:"r-20260909-6", cat:"C", artist:"Pleasure", title:"Future Now", year:1979, country:"Germany",
    tracks:["Future Now","Departure","Space Is The Place"], pLo:6, pHi:14, wildcard:false, pick:false,
    element:"NW-funk, diepe grooves + soul + futuristische textuur",
    desc:"Portland-funk voor €9: toekomstgerichte 70s soul-funk met diepe bas en kosmische sfeer — ultieme cheap-bin-vondst.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/1472085?sort=price&sort_order=asc",
    askPrice:9.30, shipEst:8, numForSale:7, cond:"", seller:"", sellerUrl:"", found:"2026-09-09" },

  { id:"r-20260909-7", cat:"C", artist:"Bobby Womack", title:"Understanding", year:1972, country:"Germany",
    tracks:["I Can Understand It","Woman's Gotta Have It","Got To Get You Back"], pLo:8, pHi:18, wildcard:false, pick:false,
    element:"soul-funk, warme stem + diepe bas + soulful arrangement",
    desc:"German press van Womack's meest groovy album: ruwe soul en 'Woman's Gotta Have It' als geheime vloer-wapen.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/4803652?sort=price&sort_order=asc",
    askPrice:12.94, shipEst:8, numForSale:7, cond:"", seller:"", sellerUrl:"", found:"2026-09-09" },

  { id:"r-20260909-8", cat:"C", artist:"Johnny Guitar Watson", title:"A Real Mother For Ya", year:1977, country:"Europe",
    tracks:["A Real Mother For Ya","The Real Deal","Tarzan"], pLo:4, pHi:12, wildcard:true, pick:false,
    element:"70s funk-rock crossover, wah-gitaar + groove + swagger",
    desc:"JGW's funky meesterwerk voor €4.88: 'A Real Mother For Ya' is een cult-klassieker die altijd in de goedkope bak slingert.",
    source:"Discogs", url:"https://www.discogs.com/sell/release/1308630?sort=price&sort_order=asc",
    askPrice:4.88, shipEst:8, numForSale:43, cond:"", seller:"", sellerUrl:"", found:"2026-09-09" },

  // ===== Batch 2026-09-11 — mystic groove-lane (handmatig gecureerd door Lars + Claude) =====
  { id:"mg-20260911-1", cat:"A", artist:"Brian Auger's Oblivion Express", title:"Closer to It!", year:1973, country:"UK",
    tracks:["Inner City Blues","Happiness Is Just Around the Bend","Compared to What"], crate:[1,5], energy:3, pLo:6, pHi:12, sublane:"mystic groove", pick:true, prio:"HIGH",
    element:"Hammond-hypnose + steady groove", desc:"Goedkoopste instap van de hele batch: overal te vinden voor een tientje, drie draaibare kanten. Orgel-groove die perfect tussen Khruangbin en jazz-funk in hangt." },
  { id:"mg-20260911-2", cat:"A", artist:"Quincy Jones", title:"You've Got It Bad Girl", year:1973, country:"US",
    tracks:["Summer in the City","Sanford & Son Theme","Superstition"], crate:[5], energy:3, pLo:6, pHi:12, sublane:"mystic groove", pick:true, prio:"HIGH",
    element:"Zwoele arrangementen + warme bas + lucht", desc:"'Summer in the City' is dé zwoele avondplaat (Pharcyde-bron). Bargain-bin-prijs, rijk gearrangeerd." },
  { id:"mg-20260911-3", cat:"A", artist:"Santana", title:"Caravanserai", year:1972, country:"US",
    tracks:["Song of the Wind","Stone Flower","Just in Time to See the Sun","All the Love of the Universe"], crate:[1,4], energy:2, pLo:8, pHi:14, sublane:"mystic groove", pick:true, prio:"HIGH",
    element:"Zingende gitaar + spiritueel-zwevende percussie", desc:"Mystic groove avant la lettre: gitaar nadrukkelijk aanwezig, hypnotisch en vol lucht. Ligt overal, betaal er niet te veel voor." },
  { id:"mg-20260911-4", cat:"A", artist:"Roy Ayers Ubiquity", title:"Vibrations", year:1976, country:"US",
    tracks:["Searching","The Memory","Vibrations"], crate:[1,5], energy:3, pLo:14, pHi:22, sublane:"mystic groove", pick:true, prio:"HIGH",
    element:"Vibrafoon-warmte + zweverige soul", desc:"'Searching' en 'The Memory' zijn kern-mystic-groove. Reissue makkelijk verkrijgbaar; origineel iets duurder." },
  { id:"mg-20260911-5", cat:"A", artist:"Johnny \"Hammond\" Smith", title:"Gears", year:1975, country:"US",
    tracks:["Los Conquistadores Chocolates","Shifting Gears","Fantasy"], crate:[1,5], energy:4, pLo:14, pHi:20, sublane:"mystic groove", pick:true, prio:"HIGH",
    element:"Mizell-productie: lagen, lucht en rollende groove", desc:"Mizell Brothers-meesterwerk. BGP-reissue betaalbaar en goed — origineel Milestone is collector." },
  { id:"mg-20260911-6", cat:"A", artist:"The Blackbyrds", title:"Action", year:1977, country:"US",
    tracks:["Mysterious Vibes","Action"], crate:[1,5], energy:3, pLo:8, pHi:15, sublane:"mystic groove", pick:true, prio:"HIGH",
    element:"Mysterieuze jazz-funk met steady pocket", desc:"'Mysterious Vibes' = titel zegt alles: precies de lane. Vaak voor onder de €15 te vinden." },
  { id:"mg-20260911-7", cat:"A", artist:"Azymuth", title:"Azimüth", year:1975, country:"Brazilië",
    tracks:["Linha do Horizonte","Melô da Cuíca"], crate:[1,4], energy:2, pLo:16, pHi:22, sublane:"mystic groove", pick:true, prio:"HIGH",
    element:"Braziliaanse zweef-fusion: Rhodes + cuíca + lucht", desc:"Debuut vol horizon-muziek; 'Linha do Horizonte' is puur mystic groove. Far Out-reissue makkelijk te krijgen." },
  { id:"mg-20260911-8", cat:"A", artist:"The Daktaris", title:"Soul Explosion", year:1998, country:"US",
    tracks:["Musicawi Silt","Eltsuhg Ibal Lasiti"], crate:[4], energy:4, pLo:14, pHi:18, pick:true, prio:"HIGH",
    element:"Rauwe afro-funk, Daptone-familie", desc:"'Musicawi Silt' is de Ethio-groove-standaard in funkvorm. Daptone-reissue ruim voorradig." },
  { id:"mg-20260911-9", cat:"A", artist:"Kokoroko", title:"Kokoroko (EP)", year:2019, country:"UK",
    tracks:["Abusey Junction","Ti-de","Uman"], crate:[4,1], energy:2, pLo:12, pHi:18, sublane:"mystic groove", pick:true, prio:"HIGH",
    element:"Zacht gloeiende gitaar + koor + geduld", desc:"'Abusey Junction' = moderne mystic groove-klassieker; sluit naadloos aan op Hermanos Gutiérrez-gevoel." },
  { id:"mg-20260911-10", cat:"A", artist:"The Temptations", title:"All Directions", year:1972, country:"US",
    tracks:["Papa Was a Rollin' Stone (albumversie 12 min)","Run Charlie Run"], crate:[5,6], energy:3, pLo:8, pHi:14, sublane:"mystic groove", pick:true, prio:"HIGH",
    element:"12 minuten hypnose: bas + hi-hat + ruimte", desc:"De lange albumversie is het hele punt — cinematische opbouw, Whitfield-productie. Goedkoop en overal." },
  { id:"mg-20260911-11", cat:"A", artist:"Isaac Hayes", title:"Hot Buttered Soul", year:1969, country:"US",
    tracks:["Walk On By","Hyperbolicsyllabicsesquedalymistic","By the Time I Get to Phoenix"], crate:[5], energy:2, pLo:12, pHi:18, sublane:"mystic groove", pick:true, prio:"HIGH",
    element:"Orkestrale traagheid + eindeloze uitbouw", desc:"'Walk On By' (12 min) is een van de beste langzame grooves ooit geperst. Talloze reissues, betaal niet te veel." },
  { id:"mg-20260911-12", cat:"A", artist:"Marvin Gaye", title:"Trouble Man", year:1972, country:"US",
    tracks:["Trouble Man","'T' Plays It Cool"], crate:[5,3], energy:2, pLo:10, pHi:16, sublane:"mystic groove", pick:true, prio:"HIGH",
    element:"Nachtelijke soundtrack-groove, Moog + strijkers", desc:"Marvins meest instrumentale, mystieke plaat — 'T' Plays It Cool is samplegoud." },
  { id:"mg-20260911-13", cat:"A", artist:"The Isley Brothers", title:"Go for Your Guns", year:1977, country:"US",
    tracks:["Footsteps in the Dark, Pts. 1 & 2","Voyage to Atlantis","Livin' in the Life"], crate:[5], energy:2, pLo:10, pHi:18, sublane:"mystic groove", pick:true, prio:"HIGH",
    element:"Zwoele steady groove + gitaarlijnen vol lucht", desc:"'Footsteps' en 'Voyage to Atlantis' zijn proto-Khruangbin. Veel persingen, goed betaalbaar." },
  { id:"mg-20260911-14", cat:"A", artist:"Oneness of Juju", title:"African Rhythms", year:1975, country:"US",
    tracks:["African Rhythms"], crate:[4,1], energy:4, pLo:18, pHi:26, sublane:"mystic groove", pick:true, prio:"HIGH",
    element:"Spiritual afro-groove mét vaste puls", desc:"Spiritueel maar de groove blijft koning — exact de balans van de lane. Koop de Strut-reissue; origineel Black Fire is collector." },
  { id:"mg-20260911-15", cat:"A", artist:"Caldera", title:"Sky Islands", year:1977, country:"US",
    tracks:["Sky Islands","Ancient Source"], crate:[1,4], energy:3, pLo:8, pHi:14, sublane:"mystic groove", prio:"MEDIUM",
    element:"Latin-fusion met zweefkwaliteit", desc:"Onderschatte bak-vondst: warm, ruimtelijk, met Dianne Reeves. Vaak spotgoedkoop in de fusion-bak." },
  { id:"mg-20260911-16", cat:"A", artist:"Lafayette Afro Rock Band", title:"Darkest Light", year:1977, country:"Frankrijk",
    tracks:["Darkest Light"], crate:[4,5], energy:3, pLo:14, pHi:20, sublane:"mystic groove", prio:"MEDIUM",
    element:"Saxofoon-hypnose + Parijse afro-funk", desc:"'Darkest Light' intro = een van de meest gesamplede ooit. Strut/Musidisc-reissues betaalbaar." },
  { id:"mg-20260911-17", cat:"A", artist:"Gene Harris", title:"Astral Signal", year:1974, country:"US",
    tracks:["Losalamitoslatinfunklovesong"], crate:[1,5], energy:2, pLo:10, pHi:18, sublane:"mystic groove", prio:"MEDIUM",
    element:"Warm zwevend Rhodes-landschap", desc:"Die ene track is de reden — en hij is het waard. Blue Note-persing redelijk vindbaar." },
  { id:"mg-20260911-18", cat:"A", artist:"Creative Source", title:"Creative Source", year:1973, country:"US",
    tracks:["Who Is He and What Is He to You?","You Can't Hide Love"], crate:[5,6], energy:3, pLo:10, pHi:18, sublane:"mystic groove", prio:"MEDIUM",
    element:"8 minuten steady sinister-soul-hypnose", desc:"Hun 'Who Is He' rekt Bill Withers op tot een trance. Ook de eerste 'You Can't Hide Love'." },
  { id:"mg-20260911-19", cat:"A", artist:"Kool & The Gang", title:"Light of Worlds", year:1974, country:"US",
    tracks:["Summer Madness","Fruitman","Light of Worlds"], crate:[5,1], energy:2, pLo:12, pHi:20, sublane:"mystic groove", prio:"MEDIUM",
    element:"'Summer Madness'-synth = pure avondmystiek", desc:"Vóór de party-hits waren ze een jazz-funkband — dit is hun zweverigste moment." },
  { id:"mg-20260911-20", cat:"A", artist:"Curtis Mayfield", title:"Back to the World", year:1973, country:"US",
    tracks:["Right On for the Darkness","Future Shock"], crate:[5], energy:3, pLo:10, pHi:18, prio:"MEDIUM",
    element:"Falsetto + wah + maatschappelijk vuur", desc:"Donkerder en hypnotischer dan Superfly. Originele Curtom-persingen betaalbaar." },
  { id:"mg-20260911-21", cat:"A", artist:"Isaac Hayes", title:"Tough Guys", year:1974, country:"US",
    tracks:["Hung Up on My Baby","Run Fay Run"], crate:[5,3], energy:2, pLo:10, pHi:18, sublane:"mystic groove", prio:"MEDIUM",
    element:"Instrumentale soundtrack-warmte, gitaar voorop", desc:"Vrijwel geheel instrumentaal — 'Hung Up on My Baby' ken je van Geto Boys. Stille Hayes-parel." },
  { id:"mg-20260911-22", cat:"A", artist:"War", title:"Why Can't We Be Friends?", year:1975, country:"US",
    tracks:["Low Rider","Why Can't We Be Friends?"], crate:[5,6], energy:4, pLo:8, pHi:14, prio:"MEDIUM",
    element:"Laidback West Coast-groove", desc:"'Low Rider' is bekend terrein maar blijft functioneel bak-gereedschap. Alleen voor een prikkie meenemen." },
  { id:"mg-20260911-23", cat:"A", artist:"Rotary Connection", title:"Hey, Love", year:1971, country:"US",
    tracks:["I Am the Black Gold of the Sun"], crate:[1,5], energy:3, pLo:15, pHi:25, sublane:"mystic groove", prio:"MEDIUM",
    element:"Psychedelische soul + Minnie Riperton-zweef", desc:"Charles Stepney-productie op z'n mystiekst. Cadet-origineel schommelt in prijs — geduld loont." },
  { id:"mg-20260911-24", cat:"A", artist:"David Axelrod", title:"Song of Innocence", year:1968, country:"US",
    tracks:["Holy Thursday","The Smile"], crate:[1,3], energy:2, pLo:18, pHi:25, sublane:"mystic groove", prio:"MEDIUM",
    element:"Cinematische drums + strijkers + ruimte", desc:"Blauwdruk voor een halve eeuw beats. Now-Again-reissue is de betaalbare route." },
  { id:"mg-20260911-25", cat:"A", artist:"CAN", title:"Future Days", year:1973, country:"Duitsland",
    tracks:["Future Days","Moonshake"], crate:[1], energy:2, pLo:18, pHi:24, sublane:"mystic groove", prio:"MEDIUM",
    element:"Motorische zweefgroove, alles ademt", desc:"Krautrock op z'n zachtst en hypnotischst — mystic groove uit een parallel universum. Spoon-reissue prima." },
  { id:"mg-20260911-26", cat:"A", artist:"Gábor Szabó", title:"Jazz Raga", year:1966, country:"Hongarije/US",
    tracks:["Mizrab","Krishna"], crate:[1,4], energy:2, pLo:16, pHi:25, sublane:"mystic groove", prio:"MEDIUM",
    element:"Gitaar + sitar-drone + trance", desc:"Gitaar nadrukkelijk aanwezig, oosterse hypnose — Light in the Attic-reissue is de betaalbare keuze." },
  { id:"mg-20260911-27", cat:"A", artist:"João Donato", title:"Quem É Quem", year:1973, country:"Brazilië",
    tracks:["A Rã"], crate:[1,4], energy:2, pLo:22, pHi:32, sublane:"mystic groove", prio:"MEDIUM",
    element:"Zachtste groove van Brazilië: Rhodes + branding", desc:"Bron-LP van 'A Rã' (niet de compilatie pakken). Polysom-reissue ~€25-30; origineel Odeon = collector." },
  { id:"mg-20260911-28", cat:"A", artist:"Sven Wunder", title:"Eastern Flowers", year:2020, country:"Zweden",
    tracks:["Lotus"], crate:[1,4], energy:3, pLo:20, pHi:26, sublane:"mystic groove", prio:"MEDIUM",
    element:"Modern library-psych, Anadolu-tinten", desc:"Hele plaat zit in de lane — moderne pers, dus prijs is wat hij is. Sluit aan op Mildlife/Yin Yin." },
  { id:"mg-20260911-29", cat:"A", artist:"Skinshape", title:"Filoxiny", year:2018, country:"UK",
    tracks:["I Didn't Know"], crate:[1,3], energy:2, pLo:18, pHi:24, sublane:"mystic groove", prio:"MEDIUM",
    element:"Dubby laidback gitaargroove", desc:"Moderne kamer-mystiek tussen Khruangbin en trip-hop in. Makkelijk nieuw/tweedehands te vinden." },
  { id:"mg-20260911-30", cat:"A", artist:"Brian Bennett", title:"Voyage (A Journey into Discoid Funk)", year:1978, country:"UK",
    tracks:["Solstice","Voyage"], crate:[1,6], energy:3, pLo:18, pHi:26, sublane:"mystic groove", prio:"MEDIUM",
    element:"Library-cosmic: synths + strakke sessiegroove", desc:"'Solstice' is de zwevendste library-disco ooit. Isle of Jura-reissue betaalbaar; origineel DJM stijgt." },
  { id:"mg-20260911-31", cat:"A", artist:"Ebo Taylor", title:"Love and Death", year:2010, country:"Ghana",
    tracks:["Love and Death"], crate:[4], energy:3, pLo:18, pHi:24, prio:"MEDIUM",
    element:"Highlife-gravitas + hypnotische gitaarfiguren", desc:"Latere Ebo maar tijdloos; Strut-persing goed verkrijgbaar." },
  { id:"mg-20260911-32", cat:"A", artist:"Gyedu-Blay Ambolley", title:"Ketan", year:1975, country:"Ghana",
    tracks:["Afrika Yie"], crate:[4], energy:3, pLo:18, pHi:24, prio:"MEDIUM",
    element:"Simigwa-funk: rauw, ritmisch, karaktervol", desc:"Mr Bongo-reissue makkelijk te vinden. NB: check bij aankoop even of 'Afrika Yie' op deze persing staat — agent valideert." },
  { id:"mg-20260911-33", cat:"A", artist:"T.P. Orchestre Poly-Rythmo / Gabo Brown", title:"Legends of Benin (comp.)", year:2009, country:"Benin",
    tracks:["It's a Vanity"], crate:[4], energy:4, pLo:20, pHi:28, prio:"MEDIUM",
    element:"Rauwe Benin-funk met hypnotische drive", desc:"'It's a Vanity' staat op deze Analog Africa 2LP — als comp meteen veel bruikbaars erbij. Origineel-45's zijn onbetaalbaar." },
  { id:"mg-20260911-34", cat:"A", artist:"Weldon Irvine", title:"Cosmic Vortex (Justice Divine)", year:1974, country:"US",
    tracks:["Walk That Walk, Talk That Talk"], crate:[1,5], energy:3, pLo:20, pHi:35, sublane:"mystic groove", prio:"MEDIUM",
    element:"Cosmic soul-jazz met boodschap", desc:"RCA-persing schaarser dan je denkt — meenemen als je 'm onder €25 ziet." },
  { id:"mg-20260911-35", cat:"A", artist:"Erick Sermon", title:"Music", year:2001, country:"US",
    tracks:["Music (feat. Marvin Gaye)"], crate:[3], energy:3, pLo:12, pHi:20, prio:"MEDIUM",
    element:"Marvin-sample + dikke laidback beat", desc:"Voor de laidback-hiphopbak; alleen de titeltrack hoeft het al waard te zijn." },
  { id:"mg-20260911-36", cat:"A", artist:"The Roots", title:"Illadelph Halflife", year:1996, country:"US",
    tracks:["What They Do","Concerto of the Desperado"], crate:[3], energy:3, pLo:25, pHi:35, prio:"MEDIUM",
    element:"Livemuzikanten + jazz-samples + warmte", desc:"2LP's uit deze era zijn prijzig — meenemen rond €25-30, niet jagen." },
  { id:"mg-20260911-37", cat:"A", artist:"The 3 Pieces", title:"Vibes of Truth", year:1975, country:"US",
    tracks:["Backed Up Against the Wall"], crate:[1,5], energy:3, pLo:18, pHi:30, sublane:"mystic groove", prio:"LOW",
    element:"Donny Hathaway-productie: verfijnde groove", desc:"PREMIUM-RANDJE: Fantasy-origineel schommelt €20-30. Alleen bij een nette prijs toeslaan." },
  { id:"mg-20260911-38", cat:"A", artist:"O'Donel Levy", title:"Simba", year:1974, country:"US",
    tracks:["Bad, Bad Simba"], crate:[5,4], energy:4, pLo:25, pHi:40, prio:"LOW",
    element:"Zware afro-jazz-funk gitaar", desc:"PREMIUM: Groove Merchant-origineel is collector-terrein en er is geen goede goedkope reissue — low priority, wachten op buitenkans." },
  { id:"mg-20260911-39", cat:"A", artist:"Weldon Irvine", title:"The Sisters", year:1979, country:"US",
    tracks:["Morning Sunrise"], crate:[1,5], energy:2, pLo:25, pHi:35, sublane:"mystic groove", prio:"LOW",
    element:"'Morning Sunrise' = tijdloze dageraad-soul", desc:"PREMIUM: origineel Nodlew is €80+. Alleen de P-Vine-reissue (~€25-35) is een verdedigbare koop." },
  { id:"mg-20260911-40", cat:"A", artist:"Slick Rick", title:"The Art of Storytelling", year:1999, country:"US",
    tracks:["Street Talkin' (feat. Outkast)"], crate:[3], energy:3, pLo:20, pHi:30, prio:"LOW",
    element:"Storytelling-flow + zuidelijke bounce", desc:"Eén approved track op een prijzige 2LP — low priority, alleen bij koopje." },
  { id:"mg-20260911-41", cat:"A", artist:"Santana", title:"Marathon", year:1979, country:"US",
    tracks:["Aqua Marine"], crate:[1], energy:2, pLo:5, pHi:10, sublane:"mystic groove", prio:"MEDIUM",
    element:"Zwevende gitaar-instrumental, ondergewaardeerde era", desc:"Alleen al voor 'Aqua Marine' — en de plaat ligt voor een vijfje in elke bak. Lage inzet, hoge zweefwaarde." }
];